version: "3.9"

services:
  node:
    build:
      context: ./docker/node
      args:
        APP_ROOT_DIR: '/usr/src/${APP_DIR}'
        APP_ENV: ${APP_ENV}
      target: 'node'
    image: 'docker.io/swordhealth/node:latest'

  mysql:
    build:
      context: ./docker/mysql
      args:
        MYSQL_DATABASE: ${MYSQL_DATABASE}
        MYSQL_USER: ${MYSQL_USER}
        MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        MYSQL_ALLOW_EMPTY_PASSWORD: ${MYSQL_ALLOW_EMPTY_PASSWORD}
      target: 'mysql'
    image: 'docker.io/swordhealth/mysql:latest'
        
  rabbitmq:
    build:
      context: ./docker/rabbitmq
      target: 'rabbitmq'
    image: 'docker.io/swordhealth/rabbitmq:latest'
