version: "3.9"

services:
  node:
    hostname: node
    image: 'docker.io/swordhealth/node:latest'
    volumes:
      - ./${APP_DIR}:/usr/src/${APP_DIR}
    env_file:
      - env/node.env
    depends_on:
      - mysql
      - rabbitmq
    ports:
      - '${APP_PORT:-80}:8080'
      
  mysql:
    hostname: mysql
    image: 'docker.io/swordhealth/mysql:latest'
    env_file:
      - env/mysql.env
    volumes:
      - './mysql/scripts:/docker-entrypoint-initdb.d:rw'
      - './mysql/data:/var/lib/mysql'
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'

  rabbitmq:
    hostname: rabbitmq
    image: 'docker.io/swordhealth/rabbitmq:latest'
    env_file:
      - env/rabbitmq.env
    ports:
      - '5672:5672'
      - '15672:15672'
      
networks:
  default:
    name: sword_health
